SERVER_IP='SERVER_HOST'

MONGO_IP='MONGO_HOST'
MONGO_PORT=27017
MONGO_RW_USER='admin'
MONGO_RW_PWD='12345'
MONGO_RO_USER='admin'
MONGO_RO_PWD='13245'
MONGO_DB='MONGO_DATABASE'

SQL_HOST='SQL_HOST'
SQL_PORT=3306
SQL_DB='SQL_DB'
SQL_RO_USER='admin'
SQL_RO_PWD='12345'

RESULTS_DIR='RESULTS_FOLDER'
TMP_RESULTS_DIR='TEMP_RESULTS_FOLDER'

SMB_IP='SAMBA_HOST'
SMB_SHARE='SAMBA_SHARE'
SMB_TIMEOUT=300
SMB_USER='guest'
SMB_PWD=''

RECONNECT_ATTEMPT=120
RECONNECT_TIME=5

SOCKET_TIMEOUT=30
ACK_TIMEOUT=450
WORKER_RESTART_TIMEOUT=600
PROGRESS_UPDATE_INTERVAL=10

ALLOWED_USERS=[]
