SERVER_IP='SERVER_HOST'
SERVER_PORT=8000

MONGO_IP='MONGO_HOST'
MONGO_PORT=27017
MONGO_RW_USER='admin'
MONGO_RW_PWD='12345'
MONGO_RO_USER='admin'
MONGO_RO_PWD='12345'
MONGO_DB='test_pleiades'

RESULTS_DIR='Results'

ALLOWED_USERS=[]
